# Funciton now used in several scripts... lets just give it one place for our sanity
renameCols <- function(x){
  vecCols <- x
  vecCols[grep("Solar Radiation", vecCols, useBytes = T)] <- "PAR"
  vecCols[grep("mm Precipitation", vecCols, useBytes = T)] <- "mm Precipitation"
  vecCols[grep("mm.Precipitation", vecCols, useBytes = T)] <- "mm.Precipitation"
  vecCols[grep("Lightning Activity", vecCols, useBytes = T)] <- "Lightning Activity"
  vecCols[grep("Lightning.Activity", vecCols, useBytes = T)] <- "Lightning.Activity"
  vecCols[grep("Lightning Distance", vecCols, useBytes = T)] <- "km Lightning Distance"
  vecCols[grep("Lightning.Distance", vecCols, useBytes = T)] <- "km.Lightning.Distance"
  vecCols[grep("Wind Direction", vecCols, useBytes = T)] <- "deg Wind Direction"
  vecCols[grep("Wind.Direction", vecCols, useBytes = T)] <- "deg.Wind.Direction"
  vecCols[grep("Wind Speed", vecCols, useBytes = T)] <- "m/s Wind Speed"
  vecCols[grep("Wind.Speed", vecCols, useBytes = T)] <- "m.s.Wind.Speed"
  vecCols[grep("Gust Speed", vecCols, useBytes = T)] <- "m/s Gust Speed"
  vecCols[grep("Gust.Speed", vecCols, useBytes = T)] <- "m.s.Gust.Speed"
  vecCols[grep("Air Temp", vecCols, useBytes = T)] <- "Air_Temp"
  vecCols[grep("Air_Temp", vecCols, useBytes = T)] <- "Air_Temp" # Putting these in just in case there's some extraneous wonk
  vecCols[grep("Vapor Press", vecCols, useBytes = T)] <- "Relative_Humidity"
  vecCols[grep("Relative Humidity", vecCols, useBytes = T)] <- "Relative_Humidity"
  vecCols[grep("Relative_Humidity", vecCols, useBytes = T)] <- "Relative_Humidity"
  vecCols[grep("Atmospheric Press", vecCols, useBytes = T)] <- "kPa Atmospheric Pressure"
  vecCols[grep("Atmospheric.Press", vecCols, useBytes = T)] <- "kPa.Atmospheric.Pressure"
  vecCols[grep("VPD", vecCols, useBytes = T)] <- "kPa VPD"
  vecCols[grep("VPD", vecCols, useBytes = T)] <- "kPa.VPD"
  vecCols[grep("X-axis", vecCols, useBytes = T)] <- "deg X-axis Level"
  vecCols[grep("X.axis", vecCols, useBytes = T)] <- "deg.X.axis.Level"
  vecCols[grep("Y-axis", vecCols, useBytes = T)] <- "deg Y-axis Level"
  vecCols[grep("Y.axis", vecCols, useBytes = T)] <- "deg.Y.axis.Level"
  vecCols[grep("Max Precip", vecCols, useBytes = T)] <- "mm/h Max Precip Rate"
  vecCols[grep("Max.Precip", vecCols, useBytes = T)] <- "mm.h.Max.Precip.Rate"
  vecCols[grep("RH Sensor Temp", vecCols, useBytes = T)] <- "degC RH Sensor Temp"
  vecCols[grep("RH.Sensor.Temp", vecCols, useBytes = T)] <- "degC.RH.Sensor.Temp"
  vecCols[grep("Water Content", vecCols, useBytes = T)] <- "Soil_Moisture"
  vecCols[grep("Soil_Moisture", vecCols, useBytes = T)] <- "Soil_Moisture"
  vecCols[grep("Soil Temp", vecCols, useBytes = T)] <- "Soil_Temp"
  vecCols[grep("Soil_Temp", vecCols, useBytes = T)] <- "Soil_Temp"
  vecCols[grep("Battery Percent", vecCols, useBytes = T)] <- "Battery Percent"
  vecCols[grep("Battery.Percent", vecCols, useBytes = T)] <- "Battery.Percent"
  vecCols[grep("Battery Voltage", vecCols, useBytes = T)] <- "mV Battery Voltage"
  vecCols[grep("Battery.Voltage", vecCols, useBytes = T)] <- "mV.Battery.Voltage"
  vecCols[grep("Reference Press", vecCols, useBytes = T)] <- "kPa Reference Pressure"
  vecCols[grep("Reference.Press", vecCols, useBytes = T)] <- "kPa.Reference.Pressure"
  vecCols[grep("Logger Temp", vecCols, useBytes = T)] <- "degC Logger Temperature"
  vecCols[grep("Logger.Temp", vecCols, useBytes = T)] <- "degC.Logger.Temperature"
  
  return(vecCols)
}